#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee -a /var/www/html/index.html > /dev/null
sudo service nginx restart
